repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
