server {
    listen 127.0.0.1:8080;
    root ./public;

    location / {
        methods GET;
        return 404;
    }

    location /307 {
        methods GET;
        return 307 https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/307;
    }

    location /redirect {
        methods GET;
        return 307 /;
    }
}
